name: sgf_parser
description: Parser library for SGF (Smart Game Format) files. Currently only supports Go.
version: 0.0.3
author: Umut Seven <umutseven92@gmail.com>
homepage: https://umutseven.com
repository: https://github.com/umutseven92/SGFParser

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: